#! /bin/sh

# execute this from parent directory

dir=$(pwd)

repos_root=../..

n_repos=0
no_parser_c=0

# XXX: find . -name parser.c also locates files that happen to
#      be named parser.c that are hand-written that are not
#      generated by tree-sitter, e.g. some things by stsewd.
#      for the moment, not using find, but the method below
#      instead.
for r in "${repos_root}"/repos/tree-sitter-*
do
    cd "${r}" || exit 1
    found=0
    n_repos=$((n_repos + 1))
    if [ -e src/parser.c ]; then
        found=1
    else
      # handling things like typescript
      for file in */src/parser.c
      do
        if [ -e "$file" ]; then
          found=1
          break
        fi
      done
    fi
    if [ 0 -eq "$found" ]; then
        printf "%s\n" "$(basename "${r}")"
        no_parser_c=$((no_parser_c + 1))
    fi
    cd "${dir}" || exit 1
done

printf "\n"

printf "Did not find parser.c in: %d\n" "${no_parser_c}"
printf "Number of repositories: %d\n" "${n_repos}"

